2023-03-01 20:22:03,111 CRITICAL server_log_config.py Критическая ошибка
2023-03-01 20:22:03,111 ERROR server_log_config.py Ошибка
2023-03-01 20:22:03,111 DEBUG server_log_config.py Отладочная информация
2023-03-01 20:22:03,111 INFO server_log_config.py Информационное сообщение
2023-03-01 20:22:13,647 INFO server.py Запущен сервер, порт для подключений: 7778, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-03-01 20:22:38,561 INFO server.py Запущен сервер, порт для подключений: 7778, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-03-01 21:00:38,735 INFO       server.py Запущен сервер, порт для подключений: 7778, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-03-01 21:00:42,406 INFO       server.py Установлено соедение с ПК ('127.0.0.1', 39432)
2023-03-01 21:00:42,406 DEBUG      utils.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1677690042.4062178, 'user': {'account_name': 'Guest'}}
2023-03-01 21:00:42,406 INFO       server.py Cформирован ответ клиенту {'response': 200}
2023-03-01 21:00:42,406 DEBUG      server.py Соединение с клиентом ('127.0.0.1', 39432) закрывается.
2023-03-04 10:55:23,837 DEBUG      server.py Была вызвана функция create_arg_parser c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main
2023-03-04 10:55:23,837 INFO       server.py Запущен сервер, порт для подключений: 7778, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2023-03-04 10:55:37,073 INFO       server.py Установлено соедение с ПК ('127.0.0.1', 36122)
2023-03-04 10:55:37,074 DEBUG      server.py Была вызвана функция receive_message c параметрами (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7778), raddr=('127.0.0.1', 36122)>,), {}. Вызов из модуля utils.Вызов из функции main
2023-03-04 10:55:37,074 DEBUG      utils.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1677912937.0738435, 'user': {'account_name': 'Guest'}}
2023-03-04 10:55:37,074 DEBUG      server.py Была вызвана функция process_client_message c параметрами ({'action': 'presence', 'time': 1677912937.0738435, 'user': {'account_name': 'Guest'}},), {}. Вызов из модуля utils.Вызов из функции main
2023-03-04 10:55:37,074 INFO       server.py Cформирован ответ клиенту {'response': 200}
2023-03-04 10:55:37,075 DEBUG      server.py Была вызвана функция send_message c параметрами (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7778), raddr=('127.0.0.1', 36122)>, {'response': 200}), {}. Вызов из модуля utils.Вызов из функции main
2023-03-04 10:55:37,075 DEBUG      server.py Соединение с клиентом ('127.0.0.1', 36122) закрывается.
